sudo: false
language: scala
script: "sbt clean test"
scala:
  - 2.11.7
jdk:
  - oraclejdk8
env:
  - SBT_OPTS="-XX:+UseConcMarkSweepGC -XX:+CMSClassUnloadingEnabled -XX:PermSize=256M -XX:MaxPermSize=512M"
# whitelist
branches:
  only:
    - master